codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default: false # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: auto  # use the coverage from the base commit (pull request base or parent commit) coverage to compare against
        threshold: null # if coverage drops, do not post a success status
        base: auto # use the pull request base if the commit is on a pull request. If not, use the parent commit
        paths: "Sources/" # only gather coverage for files in "Sources"
    patch: 
      default: false # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: auto  # use the coverage from the base commit (pull request base or parent commit) coverage to compare against
        threshold: null # if coverage drops, do not post a success status
        base: auto # use the pull request base if the commit is on a pull request. If not, use the parent commit
        paths: "Sources/" # only gather coverage for files in "Sources"
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no

# ignore:
#   - "Pods/"
#   - "Tests/"
